export const USER_LOADING = 'USER_LOADING';
export const USER_LOADED = 'USER_LOADED';
export const AUTH_ERROR = 'AUTH_ERROR';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAIL = 'LOGIN_FAIL';
export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS';
export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';
export const REGISTER_FAIL = 'REGISTER_FAIL';
export const GET_ERRORS = 'GET_ERRORS';
export const CLEAR_ERRORS = 'CLEAR_ERRORS';
export const USER_EXISTS = 'USER_EXISTS';

// For Public User
export const USER_PUBLIC_LOADING = 'USER_PUBLIC_LOADING';
export const USER_PUBLIC_LOADED = 'USER_PUBLIC_LOADED';
export const USER_PUBLIC_ERROR = 'USER_PUBLIC_ERROR';