---
apiVersion: 'v1'
kind: 'ConfigMap'
metadata:
  name: 'dbeatsfront-config-vib5'
  namespace: 'default'
  labels:
    app: 'dbeatsfront'
data:
  REACT_APP_SERVER_URL: 'https://server.dbeats.live'
---
apiVersion: 'apps/v1'
kind: 'Deployment'
metadata:
  name: 'dbeatsfront'
  namespace: 'default'
  labels:
    app: 'dbeatsfront'
spec:
  replicas: 3
  selector:
    matchLabels:
      app: 'dbeatsfront'
  template:
    metadata:
      labels:
        app: 'dbeatsfront'
    spec:
      containers:
        - name: 'dbeats-frontend-1'
          image: 'gcr.io/hazel-champion-334507/github.com/supersapiensdevlab/dbeats-frontend:$SHORT_SHA'
          env:
            - name: 'REACT_APP_SERVER_URL'
              valueFrom:
                configMapKeyRef:
                  key: 'REACT_APP_SERVER_URL'
                  name: 'dbeatsfront-config-vib5'
---
apiVersion: 'autoscaling/v2beta1'
kind: 'HorizontalPodAutoscaler'
metadata:
  name: 'dbeatsfront-hpa-yrnl'
  namespace: 'default'
  labels:
    app: 'dbeatsfront'
spec:
  scaleTargetRef:
    kind: 'Deployment'
    name: 'dbeatsfront'
    apiVersion: 'apps/v1'
  minReplicas: 1
  maxReplicas: 5
  metrics:
    - type: 'Resource'
      resource:
        name: 'cpu'
        targetAverageUtilization: 80
